# Generated by Django 2.1 on 2018-08-17 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180817_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='gotovo',
        ),
        migrations.RemoveField(
            model_name='task',
            name='zabit',
        ),
    ]
