# Generated by Django 2.1 on 2018-08-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180817_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='no',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='yes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='yesno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('yes', models.IntegerField()),
            ],
        ),
    ]
