# Generated by Django 2.1 on 2018-08-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_delete_yesno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='no',
        ),
        migrations.DeleteModel(
            name='yes',
        ),
        migrations.RemoveField(
            model_name='task',
            name='Tk',
        ),
        migrations.AddField(
            model_name='task',
            name='mg',
            field=models.CharField(default='noMessage', max_length=30),
        ),
        migrations.AddField(
            model_name='task',
            name='un',
            field=models.CharField(default='noUser', max_length=30),
        ),
    ]
