# Generated by Django 2.1 on 2018-08-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180819_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.CharField(default='noQuest', max_length=250)),
                ('otvet', models.CharField(default='noAnswer', max_length=250)),
                ('rightotvet', models.CharField(default='noAnswer', max_length=250)),
                ('ok', models.CharField(default='noAnswer', max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
