# Generated by Django 2.1 on 2018-08-20 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='person',
        ),
    ]
