# Generated by Django 2.1 on 2018-08-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='conv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.CharField(default='abc', max_length=250)),
                ('after', models.CharField(default='lol', max_length=250)),
            ],
        ),
    ]
