# Generated by Django 2.1 on 2018-08-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20180820_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodule',
            name='podskScrita',
        ),
        migrations.AlterField(
            model_name='testmodule',
            name='podsk',
            field=models.CharField(default='(Подсказка: )', max_length=250),
        ),
    ]
