# Generated by Django 2.1 on 2018-08-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20180820_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodule',
            name='podskScrita',
            field=models.CharField(default=' (Подсказка: )', max_length=250),
        ),
        migrations.AlterField(
            model_name='testmodule',
            name='podsk',
            field=models.CharField(default='.', max_length=250),
        ),
    ]
